language: java
sudo: false
jdk:
- oraclejdk7
- openjdk7
install: "./installViaTravis.sh"
script: "./buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle/caches/"
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_6efe1f7a551b_key -iv $encrypted_6efe1f7a551b_iv
  -in gradle.properties.enc -out gradle.properties -d || true
after_success:
- "./gradlew jacocoTestReport coveralls"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/36221046c5c737fe97d1
    on_success: change
    on_failure: always
    on_start: never
